name: Namma_Gadag
description: Gadag Tourist Places
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0

flutter:
  assets:
    - assets/images/
    - assets/audio/
